package com.steam.dao;

import com.steam.model.po.CourseOrder;
import com.steam.model.po.OrderExt;

import java.util.List;

public interface CourseOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbggenerated Sat Apr 20 19:46:39 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbggenerated Sat Apr 20 19:46:39 CST 2019
     */
    int insert(CourseOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbggenerated Sat Apr 20 19:46:39 CST 2019
     */
    int insertSelective(CourseOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbggenerated Sat Apr 20 19:46:39 CST 2019
     */
    CourseOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbggenerated Sat Apr 20 19:46:39 CST 2019
     */
    int updateByPrimaryKeySelective(CourseOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_order
     *
     * @mbggenerated Sat Apr 20 19:46:39 CST 2019
     */
    int updateByPrimaryKey(CourseOrder record);

    List<CourseOrder> selectList(OrderExt record);

    CourseOrder selectByOrderId(String orderId);
}