package com.steam.dao;

import com.steam.model.po.CourseCollect;
import com.steam.model.po.CourseCollectExt;

import java.util.List;

public interface CourseCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_collect
     *
     * @mbggenerated Mon Apr 22 20:47:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_collect
     *
     * @mbggenerated Mon Apr 22 20:47:56 CST 2019
     */
    int insert(CourseCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_collect
     *
     * @mbggenerated Mon Apr 22 20:47:56 CST 2019
     */
    int insertSelective(CourseCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_collect
     *
     * @mbggenerated Mon Apr 22 20:47:56 CST 2019
     */
    CourseCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_collect
     *
     * @mbggenerated Mon Apr 22 20:47:56 CST 2019
     */
    int updateByPrimaryKeySelective(CourseCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_collect
     *
     * @mbggenerated Mon Apr 22 20:47:56 CST 2019
     */
    int updateByPrimaryKey(CourseCollect record);

    List<CourseCollect> selectList(CourseCollectExt record);

    CourseCollect selectOne(CourseCollectExt record);
}