package com.steam.dao;

import com.steam.model.po.Point;
import com.steam.model.po.PointExt;

import java.util.List;

public interface PointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    int insert(Point record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    int insertSelective(Point record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    Point selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    int updateByPrimaryKeySelective(Point record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    int updateByPrimaryKey(Point record);

    List<Point> selectList(PointExt record);
}