package com.steam.dao;

import com.steam.model.po.UserLogin;
import com.steam.model.po.UserLoginExt;

import java.util.List;

public interface UserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    int insert(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    int insertSelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    UserLogin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    int updateByPrimaryKeySelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    int updateByPrimaryKey(UserLogin record);

    List<UserLogin> selectList(UserLoginExt criteria);
}