package com.steam.model.po;

import java.math.BigDecimal;
import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_info
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String courseInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_pic
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String coursePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.video_url
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_type
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String courseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price_type
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String priceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_name
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_info
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String teacherInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.merchant_name
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.merchant_info
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private String merchantInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.create_time
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.update_time
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_info
     *
     * @return the value of course.course_info
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getCourseInfo() {
        return courseInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_info
     *
     * @param courseInfo the value for course.course_info
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setCourseInfo(String courseInfo) {
        this.courseInfo = courseInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_pic
     *
     * @return the value of course.course_pic
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getCoursePic() {
        return coursePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_pic
     *
     * @param coursePic the value for course.course_pic
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setCoursePic(String coursePic) {
        this.coursePic = coursePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.video_url
     *
     * @return the value of course.video_url
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.video_url
     *
     * @param videoUrl the value for course.video_url
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_type
     *
     * @return the value of course.course_type
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_type
     *
     * @param courseType the value for course.course_type
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setCourseType(String courseType) {
        this.courseType = courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price_type
     *
     * @return the value of course.price_type
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price_type
     *
     * @param priceType the value for course.price_type
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price
     *
     * @return the value of course.price
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price
     *
     * @param price the value for course.price
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_name
     *
     * @return the value of course.teacher_name
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_name
     *
     * @param teacherName the value for course.teacher_name
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_info
     *
     * @return the value of course.teacher_info
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getTeacherInfo() {
        return teacherInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_info
     *
     * @param teacherInfo the value for course.teacher_info
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setTeacherInfo(String teacherInfo) {
        this.teacherInfo = teacherInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.merchant_name
     *
     * @return the value of course.merchant_name
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.merchant_name
     *
     * @param merchantName the value for course.merchant_name
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.merchant_info
     *
     * @return the value of course.merchant_info
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public String getMerchantInfo() {
        return merchantInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.merchant_info
     *
     * @param merchantInfo the value for course.merchant_info
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setMerchantInfo(String merchantInfo) {
        this.merchantInfo = merchantInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.create_time
     *
     * @return the value of course.create_time
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.create_time
     *
     * @param createTime the value for course.create_time
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.update_time
     *
     * @return the value of course.update_time
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.update_time
     *
     * @param updateTime the value for course.update_time
     *
     * @mbggenerated Tue Apr 16 20:09:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}