package com.steam.model.po;

import java.util.Date;

public class Point {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.id
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.uid
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.source
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.point_value
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    private Integer pointValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.create_time
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.update_time
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.id
     *
     * @return the value of point.id
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.id
     *
     * @param id the value for point.id
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.uid
     *
     * @return the value of point.uid
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.uid
     *
     * @param uid the value for point.uid
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.source
     *
     * @return the value of point.source
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.source
     *
     * @param source the value for point.source
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.point_value
     *
     * @return the value of point.point_value
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public Integer getPointValue() {
        return pointValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.point_value
     *
     * @param pointValue the value for point.point_value
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public void setPointValue(Integer pointValue) {
        this.pointValue = pointValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.create_time
     *
     * @return the value of point.create_time
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.create_time
     *
     * @param createTime the value for point.create_time
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.update_time
     *
     * @return the value of point.update_time
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.update_time
     *
     * @param updateTime the value for point.update_time
     *
     * @mbggenerated Mon Mar 18 23:51:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}