package com.steam.model.po;

import java.util.Date;

public class UserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.id
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.uid
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.token
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.login_time
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.expired_time
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    private Date expiredTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.id
     *
     * @return the value of user_login.id
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.id
     *
     * @param id the value for user_login.id
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.uid
     *
     * @return the value of user_login.uid
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.uid
     *
     * @param uid the value for user_login.uid
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.token
     *
     * @return the value of user_login.token
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.token
     *
     * @param token the value for user_login.token
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.login_time
     *
     * @return the value of user_login.login_time
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.login_time
     *
     * @param loginTime the value for user_login.login_time
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.expired_time
     *
     * @return the value of user_login.expired_time
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.expired_time
     *
     * @param expiredTime the value for user_login.expired_time
     *
     * @mbggenerated Mon Mar 11 21:50:05 CST 2019
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }
}